spring:
  application:
    name: library-service
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    sender:
      type: WEB
    service:
      name: library-service
  sleuth:
    enabled: true
    sampler:
      probability: 1

server:
  port: 8083
